config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#index'

  get "jonnienguyen", to: "pages#jonnienguyen", as: "jonnienguyen"
  get 'AmandaANgo', to: 'pages#AmandaANgo', as: 'amandaANgo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def jonnienguyen
  end
  
  def AmandaANgo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamCollab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/AmandaANgo.html.erb
<h1>Amanda Ngo</h1>

<u1> I am a junior computer science major.</ul>

<p> I do not know what I am doing.</p>

app/views/pages/LAKSHMANA.html.erb
<h1>LAKSHMANA</h1>

app/views/pages/SingleVIP.html.erb
<h1>SingleVIP</h1>
 
<p>
  Something interesting about me
</p>
 
<p>
  Something not so interesting about me
</p>

app/views/pages/index.html.erb
<h1>Directory of Student Pages</h1>

<ul>
    <li><%= link_to "jonnienguyen", jonnienguyen_path %></li>
    <li><%= link_to 'AmandaANgo', amandaANgo_path %></li>
</ul>

app/views/pages/jonnienguyen.html.erb
<h1>Hello, my name is Jonnie Nguyen</h1>

<p>I am tried and sleepy (zzz...). Here is me counting to 5 sheeps...</p>